# Generated by Django 4.2.2 on 2024-01-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AddField(
            model_name='supplier',
            name='invoice_number',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='item_name',
            field=models.CharField(default='any', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='item_number',
            field=models.CharField(default='any', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='any', max_length=255),
        ),
    ]
